version: '3'
services:
  guacdb:
    container_name: guacamoledb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'MariaDBRootPass'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user'
      MYSQL_PASSWORD: 'MariaDBUserPass'
    volumes:
      - 'db-data:/var/lib/mysql'
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacdb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "MariaDBUserPass"
      TOTP_ENABLED: "false"
      WEBAPP_CONTEXT: ROOT
    depends_on:
      - guacdb
      - guacd
volumes:
  db-data: